# Generated by Django 2.1 on 2018-08-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('label', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', through='stock.IngredientStock', to='stock.Restaurant'),
        ),
    ]
