# Generated by Django 2.1 on 2018-08-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20180809_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredients',
            new_name='restaurant',
        ),
    ]
