# Generated by Django 2.1 on 2018-08-09 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20180809_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Product')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='restaurant',
            field=models.ManyToManyField(related_name='products', through='stock.ProductStock', to='stock.Restaurant'),
        ),
    ]
