# Generated by Django 2.1 on 2018-08-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20180809_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('label', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('pizzas', models.ManyToManyField(related_name='menus', to='stock.Pizza')),
                ('products', models.ManyToManyField(related_name='menus', to='stock.Product')),
            ],
        ),
    ]
