# Generated by Django 2.1 on 2018-08-10 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0006_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PanierMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Menu')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Panier')),
            ],
        ),
        migrations.CreateModel(
            name='PanierPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Panier')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Pizza')),
            ],
        ),
        migrations.CreateModel(
            name='PanierProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Panier')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Product')),
            ],
        ),
        migrations.AddField(
            model_name='panier',
            name='menus',
            field=models.ManyToManyField(related_name='paniers', through='order.PanierMenu', to='stock.Menu'),
        ),
        migrations.AddField(
            model_name='panier',
            name='pizzas',
            field=models.ManyToManyField(related_name='paniers', through='order.PanierPizza', to='stock.Pizza'),
        ),
        migrations.AddField(
            model_name='panier',
            name='products',
            field=models.ManyToManyField(related_name='paniers', through='order.PanierProduct', to='stock.Product'),
        ),
    ]
